server:
  port: 8091
#server:
#  port: 8080
spring:
  datasource:
#    url: jdbc:oracle:thin:@192.168.101.150:1521:orcl
    url: jdbc:oracle:thin:@183.239.33.103:15223:orcl
    username: jzcxForVx
    password: jzcxForVx
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

