spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.101.150:1521:orcl
    username: jzcx
    password: jzcx2019
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
